### ISSUE TITLE
Ask about importing masks from other software?

### ISSUE THREAD

**Issue by D-Mad** [max810/XMem2#9]
I used

python import_existing.py --name <name_of_the_project_to_create> [--images <path_to_folder_with_frames>] [--mask <path_to_folder_with_masks>]

But when imported, it appears

![image](https://github.com/max810/XMem2/assets/8207507/0f3268b4-97fa-483f-847d-469cf6c48ae9)

but I only draw 1 object

**Comment by maksymbekuzarovSC** [comment]
Please refer to this doc for help: [docs/DATA_FORMAT_HELP.md](https://github.com/max810/XMem2/blob/main/docs/DATA_FORMAT_HELP.md#color-scheme-palette), pay attention to the illustration.

It seems to me that the mask you created has a lot of different colors instead of 2 (black + another one), this typically happens when you are using any interpolation other than Nearest Neighbour.

**Each unique color is treated by XMem++ as a new object (besides black, which is background).** 

You can check this by running the following code:

```Python
from PIL import Image

print(Image.open("<path to your mask>").getcolors())
```

If there are more than `num_objects + 1`, then this mask is invalid.
